const phaseData={vegetatif:{title:'Perlindungan Awal (0–40 HST)',items:['Kendalikan gulma hingga tuntas','Pencegahan sundep & pelipat daun','Waspada terhadap penyakit blast dan bercak cokelat','Maksimalkan pembentukan dan pertumbuhan anakan padi']},reproduktif:{title:'Proteksi Malai dan Bulir (40–60 HST)',items:['Proteksi dari serangan beluk & pelipat daun','Waspadai penyakit blast daun & potong leher','Jaga kesehatan daun bendera, bulir, dan malai padi']},pemasakan:{title:'Kualitas & Bobot (60–90 HST)',items:['Pantau penyakit gosong palsu','Dukung pengisian bulir gabah dengan optimal','Jaga kualitas bulir menjelang panen']}};
document.querySelectorAll('.phase').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.phase').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=phaseData[b.dataset.phase];document.getElementById('phaseTitle').textContent=d.title;document.getElementById('phaseItems').innerHTML=d.items.map(x=>`<li>${x}</li>`).join('')}));
document.querySelectorAll('.track button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.track button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('timeTitle').textContent=b.dataset.title;document.getElementById('timeCopy').textContent=b.dataset.copy}));
const n=id=>Math.max(0,Number(document.getElementById(id).value)||0);const fmt=x=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(x);
function dose(){let r=n('rate'),a=n('area'),v=n('volume');document.getElementById('doseResult').textContent=fmt(r*a/10000)+' ml atau g';document.getElementById('concentration').textContent='Konsentrasi teoritis: '+fmt(v?r/v:0)+' ml atau g/L'}
function roi(){let revenue=n('gain')*n('price'),extra=n('packCost')-n('farmCost');document.getElementById('revenue').textContent='Rp '+fmt(revenue);document.getElementById('net').textContent='Selisih biaya: Rp '+fmt(extra)+' · Simulasi setelah selisih biaya: Rp '+fmt(revenue-extra)}
['rate','area','volume'].forEach(id=>document.getElementById(id).addEventListener('input',dose));['gain','price','packCost','farmCost'].forEach(id=>document.getElementById(id).addEventListener('input',roi));dose();roi();
const toggle=document.getElementById('menuToggle'),links=document.getElementById('navLinks');toggle.addEventListener('click',()=>links.classList.toggle('open'));links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));

// OPT categories and individual field-guide entries use native accessible details/summary elements.
